### ISSUE TITLE
URL Constants

### ISSUE THREAD

**Issue by patzielinski** [Samkit-shah/SoftwareSupplyChainSecurity-hw1#1]
Utilizing a constant for the part of the URL that doesn't change across different queries might help condense some of these function calls, e.g. `REKOR_API = https://rekor.sigstore.dev/api/v1/log` or something similar. Unsure if this affects f-strings though.

https://github.com/Samkit-shah/SoftwareSupplyChainSecurity-hw1/blob/5734d107c73521b5c9d190b02ae329eb37a77e6c/main.py#L9

**Comment by Samkit-shah** [comment]
Fixed in this [PR](https://github.com/Samkit-shah/SoftwareSupplyChainSecurity-hw1/pull/7)
