### ISSUE TITLE
Argument Checking

### ISSUE THREAD

**Issue by patzielinski** [Samkit-shah/SoftwareSupplyChainSecurity-hw1#2]
I think it might be good to check the int here to ensure it's nonnegative before calling the Rekor API.

https://github.com/Samkit-shah/SoftwareSupplyChainSecurity-hw1/blob/5734d107c73521b5c9d190b02ae329eb37a77e6c/main.py#L24

**Comment by Samkit-shah** [comment]
Fixed in [this](https://github.com/Samkit-shah/SoftwareSupplyChainSecurity-hw1/pull/8) PR
