### ISSUE TITLE
Docstrings

### ISSUE THREAD

**Issue by patzielinski** [Samkit-shah/SoftwareSupplyChainSecurity-hw1#3]
I know these functions are rather simple, but a short docstring would help to clarify them for users who may be unsure of what they do.

https://github.com/Samkit-shah/SoftwareSupplyChainSecurity-hw1/blob/5734d107c73521b5c9d190b02ae329eb37a77e6c/main.py#L134

**Comment by Samkit-shah** [comment]
Fix in [this](https://github.com/Samkit-shah/SoftwareSupplyChainSecurity-hw1/pull/9) PR
