### ISSUE TITLE
Simplify conditionals and return value handling

### ISSUE THREAD

**Issue by JacksonQu** [Samkit-shah/SoftwareSupplyChainSecurity-hw1#4]
https://github.com/Samkit-shah/SoftwareSupplyChainSecurity-hw1/blob/5734d107c73521b5c9d190b02ae329eb37a77e6c/merkle_proof.py#L90

Delete `else:`  to reduce unnecessary conditional statements.

```
if calculated != expected:
    raise RootMismatchError(expected, calculated)
return True
```

**Comment by Samkit-shah** [comment]
Fixed in [this](https://github.com/Samkit-shah/SoftwareSupplyChainSecurity-hw1/pull/10) PR
