### ISSUE TITLE
Remove unnecessary pass statements

### ISSUE THREAD

**Issue by JacksonQu** [Samkit-shah/SoftwareSupplyChainSecurity-hw1#5]
https://github.com/Samkit-shah/SoftwareSupplyChainSecurity-hw1/blob/5734d107c73521b5c9d190b02ae329eb37a77e6c/main.py#L131

https://github.com/Samkit-shah/SoftwareSupplyChainSecurity-hw1/blob/5734d107c73521b5c9d190b02ae329eb37a77e6c/main.py#L94

https://github.com/Samkit-shah/SoftwareSupplyChainSecurity-hw1/blob/5734d107c73521b5c9d190b02ae329eb37a77e6c/main.py#L48

Remove the unnecessary `pass` statements, making the code look cleaner.

**Comment by Samkit-shah** [comment]
Fixed in [this](https://github.com/Samkit-shah/SoftwareSupplyChainSecurity-hw1/pull/11) PR
