### ISSUE TITLE
Log detailed exception information

### ISSUE THREAD

**Issue by JacksonQu** [Samkit-shah/SoftwareSupplyChainSecurity-hw1#6]
https://github.com/Samkit-shah/SoftwareSupplyChainSecurity-hw1/blob/5734d107c73521b5c9d190b02ae329eb37a77e6c/util.py#L57

Log detailed exception information for further error handling.

```
logging.error("Invalid signature for artifact: %s", artifact_filename)
```

Similarly, 
```
logging.error("Exception in verifying artifact signature for %s: %s", artifact_filename, e)
```

**Comment by Samkit-shah** [comment]
Fixed in [this](https://github.com/Samkit-shah/SoftwareSupplyChainSecurity-hw1/pull/12) PR
